gui:
  # Expanded by default
  showFileTree: true
  showRandomTip: false
  showCommandLog: false
  nerdFontsVersion: "3"
git:
  pagers:
    - pager: diff-so-fancy
keybinding:
  universal:
    quit: "q"
    togglePanel: "<tab>"
refresher:
  refreshInterval: 10 # seconds
promptToReturnFromSubprocess: false
